services:
  - type: web
    name: UIReplicator
    env: node
    buildCommand: npm install --include=dev && chmod +x render-build.sh && ./render-build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
