services:
  - type: web
    name: beyond-grooming
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node run-static.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLICKSEND_USERNAME
        sync: false
      - key: CLICKSEND_API_KEY
        sync: false